### ISSUE TITLE
Unable to use EDAPI plugin

### ISSUE THREAD

**Issue by MarkAusten** [eyeonus/Trade-Dangerous#57]
I'm getting an error on calling the edapi plugin as pasted below. The command is being run from a console window in the same folder as the TD data and tmp folders. I have updated TD to the latest version via pip. I have cut out the path to the python folder to improve readability.

This is with a fresh install of TD.

Thanks.

Error log:

`C:\Development\TDHelper\TradeDangerousGUI\bin\Debug>trade import -P edapi -O tdh`
`Traceback (most recent call last):`
`  File "...\python37\lib\runpy.py", line 193, in _run_module_as_main`
`    "__main__", mod_spec)`
`  File "...\python37\lib\runpy.py", line 85, in _run_code`
`    exec(code, run_globals)`
`  File "...\Python37\Scripts\trade.exe\__main__.py", line 9, in <module>`
`  File "...\python37\lib\site-packages\tradedangerous\cli.py", line 70, in main`
`    trade(argv)`
`  File "...\python37\lib\site-packages\tradedangerous\cli.py", line 125, in trade`
`    results = cmdenv.run(tdb)`
`  File "...\python37\lib\site-packages\tradedangerous\commands\commandenv.py", line 81, in run`
`    return self._cmd.run(results, self, tdb)`
`  File "...\python37\lib\site-packages\tradedangerous\commands\import_cmd.py", line 122, in run`
`    if not plugin.run():`
`  File "...\python37\lib\site-packages\tradedangerous\plugins\edapi_plug.py", line 748, in run`
`    if tdh_path.exists():`
`AttributeError: 'str' object has no attribute 'exists'`

**Comment by eyeonus** [comment]
Apparently the relevant line got broken in fca7f2698a5ac83dd4011c4dcd3379d9cbed0274 and just wasn't noticed until now.
